require 'rake/sprocketstask'

env = Sprockets::Environment.new
env.append_path("./src/asset/javascript")
env.append_path("./src/asset/scss")

Rake::SprocketsTask.new do |t|
    t.environment = env
    t.output      = "./public/assets"
    t.assets      = %w( application.js application.scss )
end
